package com.ccsw.tutorial.exception;

import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.ResponseStatus;

@ResponseStatus(code = HttpStatus.BAD_REQUEST, reason = "Client name already exists")
public class ClientNameAlreadyExistsException extends RuntimeException {

    /**
     * Generated by Eclipse
     */
    private static final long serialVersionUID = -163029299223220669L;

    public ClientNameAlreadyExistsException(){
        super();
    }
    
    public ClientNameAlreadyExistsException(String msg){
        super(msg);
    }
}
