package com.ccsw.tutorial.exception;

import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.ResponseStatus;

/**
 * 
 * @author caliagaq
 *
 */
@ResponseStatus(code = HttpStatus.BAD_REQUEST, reason = "Game not available on those dates")
public class GameNotAvailableException extends RuntimeException {

    /**
     * Generated by Eclipse
     */
    private static final long serialVersionUID = -8854339202004555033L;

    public GameNotAvailableException(){
        super();
    }
    
    public GameNotAvailableException(String msg){
        super(msg);
    }
}
