package com.ccsw.tutorial.exception;

import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.ResponseStatus;

/**
 * 
 * @author caliagaq
 *
 */
@ResponseStatus(code = HttpStatus.BAD_REQUEST, reason = "Loan period exceeds 14 days")
public class LoanPeriodTooLongException extends RuntimeException {

    /**
     * Generated by Eclipse
     */
    private static final long serialVersionUID = -6733389532855028958L;

    public LoanPeriodTooLongException(){
        super();
    }
    
    public LoanPeriodTooLongException(String msg){
        super(msg);
    }
}
